From SimpleC.EE.CAV.verify_20260614_hil_xizi_single_link_empty Require Import xizi_single_link_empty_goal xizi_single_link_empty_proof_auto xizi_single_link_empty_proof_manual.

Module VC_Correctness : VC_Correct.
  Include xizi_single_link_empty_proof_auto.
  Include xizi_single_link_empty_proof_manual.
End VC_Correctness.
