From SimpleC.EE.CAV.verify_20260614_hil_xizi_single_link_init Require Import xizi_single_link_init_goal xizi_single_link_init_proof_auto xizi_single_link_init_proof_manual.

Module VC_Correctness : VC_Correct.
  Include xizi_single_link_init_proof_auto.
  Include xizi_single_link_init_proof_manual.
End VC_Correctness.
