From SimpleC.EE.CAV.verify_20260602_170722v_xizi_circular_area_state Require Import xizi_circular_area_state_goal xizi_circular_area_state_proof_auto xizi_circular_area_state_proof_manual.

Module VC_Correctness : VC_Correct.
  Include xizi_circular_area_state_proof_auto.
  Include xizi_circular_area_state_proof_manual.
End VC_Correctness.
