From SimpleC.EE.CAV.verify_20260602_151223v_xizi_dataqueue_empty Require Import xizi_dataqueue_empty_goal xizi_dataqueue_empty_proof_auto xizi_dataqueue_empty_proof_manual.

Module VC_Correctness : VC_Correct.
  Include xizi_dataqueue_empty_proof_auto.
  Include xizi_dataqueue_empty_proof_manual.
End VC_Correctness.
