From SimpleC.EE.CAV.ground_truth_p056_correct_bracketing Require Import p056_correct_bracketing_goal p056_correct_bracketing_proof_auto p056_correct_bracketing_proof_manual.

Module VC_Correctness : VC_Correct.
  Include char_array_strategy_proof.
  Include p056_correct_bracketing_proof_auto.
  Include p056_correct_bracketing_proof_manual.
End VC_Correctness.
