Require Import Coq.ZArith.ZArith.
Require Import Coq.Bool.Bool.
Require Import Coq.Strings.String.
Require Import Coq.Strings.Ascii.
Require Import Coq.Lists.List.
Require Import Coq.Classes.RelationClasses.
Require Import Coq.Classes.Morphisms.
Require Import Coq.micromega.Psatz.
Require Import Coq.Sorting.Permutation.
From AUXLib Require Import int_auto Axioms Feq Idents ListLib VMap.
Require Import SetsClass.SetsClass. Import SetsNotation.
From SimpleC.SL Require Import Mem SeparationLogic.
From SimpleC.EE.CAV.ground_truth_p136_largest_smallest_integers Require Import p136_largest_smallest_integers_goal.
Require Import Logic.LogicGenerator.demo932.Interface.
Local Open Scope Z_scope.
Local Open Scope sets.
Local Open Scope string_scope.
Local Open Scope list.
Import naive_C_Rules.
Require Import p136_largest_smallest_integers.
Local Open Scope sac.

Lemma proof_of_p136_largest_smallest_integers_safety_wit_1 : p136_largest_smallest_integers_safety_wit_1.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_2 : p136_largest_smallest_integers_safety_wit_2.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_3 : p136_largest_smallest_integers_safety_wit_3.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_4 : p136_largest_smallest_integers_safety_wit_4.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_5 : p136_largest_smallest_integers_safety_wit_5.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_6 : p136_largest_smallest_integers_safety_wit_6.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_7 : p136_largest_smallest_integers_safety_wit_7.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_8 : p136_largest_smallest_integers_safety_wit_8.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_9 : p136_largest_smallest_integers_safety_wit_9.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_10 : p136_largest_smallest_integers_safety_wit_10.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_11 : p136_largest_smallest_integers_safety_wit_11.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_12 : p136_largest_smallest_integers_safety_wit_12.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_13 : p136_largest_smallest_integers_safety_wit_13.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_14 : p136_largest_smallest_integers_safety_wit_14.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_15 : p136_largest_smallest_integers_safety_wit_15.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_16 : p136_largest_smallest_integers_safety_wit_16.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_17 : p136_largest_smallest_integers_safety_wit_17.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_18 : p136_largest_smallest_integers_safety_wit_18.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_19 : p136_largest_smallest_integers_safety_wit_19.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_20 : p136_largest_smallest_integers_safety_wit_20.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_21 : p136_largest_smallest_integers_safety_wit_21.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_22 : p136_largest_smallest_integers_safety_wit_22.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_23 : p136_largest_smallest_integers_safety_wit_23.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_safety_wit_24 : p136_largest_smallest_integers_safety_wit_24.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_1 : p136_largest_smallest_integers_partial_solve_wit_1.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_2 : p136_largest_smallest_integers_partial_solve_wit_2.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_3 : p136_largest_smallest_integers_partial_solve_wit_3.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_4 : p136_largest_smallest_integers_partial_solve_wit_4.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_5 : p136_largest_smallest_integers_partial_solve_wit_5.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_6 : p136_largest_smallest_integers_partial_solve_wit_6.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_7 : p136_largest_smallest_integers_partial_solve_wit_7.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_8 : p136_largest_smallest_integers_partial_solve_wit_8.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_9 : p136_largest_smallest_integers_partial_solve_wit_9.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_10 : p136_largest_smallest_integers_partial_solve_wit_10.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_11 : p136_largest_smallest_integers_partial_solve_wit_11.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_12 : p136_largest_smallest_integers_partial_solve_wit_12.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_13_pure : p136_largest_smallest_integers_partial_solve_wit_13_pure.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_13 : p136_largest_smallest_integers_partial_solve_wit_13.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_14 : p136_largest_smallest_integers_partial_solve_wit_14.
Proof. Admitted. 

Lemma proof_of_p136_largest_smallest_integers_partial_solve_wit_15 : p136_largest_smallest_integers_partial_solve_wit_15.
Proof. Admitted. 

